{"name": "Проверка ошибки при входе в систему с неверными данными для тестов", "status": "passed", "description": "Запрос входа с неверными данными для проверки, подтверждение ответа", "start": 1717874807176, "stop": 1717874807278, "uuid": "614fb37e-5c84-4be1-89fa-6a39f3b1e9f7", "historyId": "c0e778e85752b842b77904011e5860e3", "testCaseId": "c0e778e85752b842b77904011e5860e3", "fullName": "test_login_courier.TestCourierLogin#test_courier_login_null_data", "labels": [{"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "antonov-pc"}, {"name": "thread", "value": "17960-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_courier"}]}